import tkinter
from discord_webhook import DiscordWebhook
def sender():
    wlink = link_entry.get()
    name = name_entry.get()
    aurl = avatar_entry.get()
    mess = mess_entry.get()
    number = number_entry.get()
    for t in range(int(number)):
        webhook = DiscordWebhook(url=wlink, content=mess, username=name, avatar_url=aurl)
        response = webhook.execute()
root = tkinter.Tk()
root.title("Discord Webhook Sender")
root.geometry("300x150")
link_label = tkinter.Label(root, text="Webhook")
link_entry = tkinter.Entry(root)
name_label=tkinter.Label(root, text="Username") 
name_entry = tkinter.Entry(root)
avatar_label=tkinter.Label(root, text="Avatar URL") 
avatar_entry = tkinter.Entry(root)
mess_label=tkinter.Label(root, text="Message") 
mess_entry = tkinter.Entry(root)
number_label=tkinter.Label(root, text="Message Number") 
number_entry = tkinter.Entry(root)
send_button = tkinter.Button(root, text="Send Message", command=sender)
link_label.pack()
link_entry.pack()
name_label.pack()
name_entry.pack()
avatar_label.pack()
avatar_entry.pack()
mess_label.pack()
mess_entry.pack()
number_label.pack()
number_entry.pack()
send_button.pack()
root.mainloop()
